//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.PortfolioDatas = new HashSet<PortfolioData>();
            this.ScripMappers = new HashSet<ScripMapper>();
            this.Transactions = new HashSet<Transaction>();
            this.Watchlists = new HashSet<Watchlist>();
        }
    
        public int CID { get; set; }
        public string Name { get; set; }
        public string Scrip { get; set; }
        public string ExchangeName { get; set; }
        public string Sector { get; set; }
        public string URL { get; set; }
    
        public virtual Alert Alert { get; set; }
        public virtual ICollection<PortfolioData> PortfolioDatas { get; set; }
        public virtual ICollection<ScripMapper> ScripMappers { get; set; }
        public virtual StockData StockData { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Watchlist> Watchlists { get; set; }
    }
}
