//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioData
    {
        public int PID { get; set; }
        public int CID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CurrentHolding { get; set; }
        public Nullable<decimal> RealizedProfitLoss { get; set; }
        public Nullable<decimal> UnrealizedProfitLoss { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Portfolio Portfolio { get; set; }
    }
}
