//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceAlert
    {
        public int alertID { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> tolerance { get; set; }
    
        public virtual Alert Alert { get; set; }
    }
}
