//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScripMapper
    {
        public int CID { get; set; }
        public int SourceID { get; set; }
        public string ScripCode { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual SourceInfo SourceInfo { get; set; }
    }
}
