//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockData
    {
        public int CID { get; set; }
        public Nullable<decimal> LTP { get; set; }
        public string LTPTime { get; set; }
        public Nullable<decimal> Change { get; set; }
        public Nullable<decimal> PercChange { get; set; }
        public Nullable<decimal> DayOpen { get; set; }
        public Nullable<decimal> PrevClose { get; set; }
        public Nullable<decimal> DayHigh { get; set; }
        public Nullable<decimal> DayLow { get; set; }
        public Nullable<decimal> Week52High { get; set; }
        public Nullable<decimal> Week52Low { get; set; }
        public string Volume { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
