//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects.DataClasses;
    
    public partial class StockManagerEntities : DbContext
    {
        public StockManagerEntities()
            : base("name=StockManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Alert> Alerts { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<LoginInfo> LoginInfoes { get; set; }
        public DbSet<Portfolio> Portfolios { get; set; }
        public DbSet<PortfolioData> PortfolioDatas { get; set; }
        public DbSet<PriceAlert> PriceAlerts { get; set; }
        public DbSet<ScripMapper> ScripMappers { get; set; }
        public DbSet<SourceInfo> SourceInfoes { get; set; }
        public DbSet<StockData> StockDatas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeAlert> TimeAlerts { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<Watchlist> Watchlists { get; set; }
    }
}
