//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watchlist
    {
        public Watchlist()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int WatchlistId { get; set; }
        public string WLName { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
