//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.PortfolioDatas = new HashSet<PortfolioData>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual ICollection<PortfolioData> PortfolioDatas { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
