//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceInfo
    {
        public SourceInfo()
        {
            this.ScripMappers = new HashSet<ScripMapper>();
        }
    
        public int SourceID { get; set; }
        public string SourceName { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<ScripMapper> ScripMappers { get; set; }
    }
}
